services:
  tailnet-qemu:
    build: .
    image: ghcr.io/sudosu404/tailnet-qemu:latest
    container_name: tailnet-qemu
    environment:
      BOOT: "boot.iso"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net
      - /dev/vhost-vsock
      - /dev/ttyS0
      - /dev/sdd
      - /dev/fuse
      - /dev/ptmx
      - /dev/hwrng
      - /dev/fuse
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    dns:
      - 172.30.0.3
    ports:
      - 8006:8006
    volumes:
      - ./storage:/storage
    restart: always
    stop_grace_period: 2m
