services:
  tailnet-qemu:
    build: .
    image: ghcr.io/sudosu404/tailnet-qemu:latest
    environment:
      BOOT: "boot.iso"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net
      - /dev/vhost-vsock
      - /dev/ttyS0
      - /dev/sdd
      - /dev/fuse
      - /dev/ptmx
      - /dev/hwrng
      - /dev/fuse
    device_cgroup_rules:
      - 'c *:* rwm'
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "pve"
      tsdproxy.container_port: 8006
    dns:
      - 172.30.0.3
    volumes:
      - ./storage:/storage
    restart: always
    stop_grace_period: 2m
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsdproxydata:/data
    environment:
      # Get AuthKey from your Tailscale account
      - TSDPROXY_AUTHKEY=${TSDPROXY_AUTHKEY}
      # Address of docker server (access to example.com ports)
      - TSDPROXY_HOSTNAME=${TSDPROXY_HOSTNAME}
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped

volumes:
  tsdproxydata:
